[env:rpipico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board_build.core = earlephilhower
board = rpipico
framework = arduino

upload_protocol = picotool
upload_port = COM8
monitor_port = COM8
monitor_speed = 115200
extra_scripts = pre:scripts/pico_pre_upload.py

; LittleFS 파티션 크기: 512KB
board_build.filesystem_size = 512k

lib_deps =
    lovyan03/LovyanGFX @ ^1.2.0
    bblanchon/ArduinoJson @ ^6.21.5
    claws/BH1750 @ ^1.3.0

build_flags =
    -std=gnu++17
    -D LGFX_USE_V1
    -O2
    -DCORE_DEBUG_LEVEL=3
    -I src
    -I include

; Normal run mode: Pico Serial (Interface 0)(COM8)
; BOOTSEL mode: RP2 Boot (Interface 1)(COM11) - do not use as upload_port
